# Generated by Django 3.0.3 on 2020-02-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourshare', '0002_group_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('people', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='image',
        ),
    ]
